version: '3.8'

services:
  # --- SERVIÇO DO BANCO DE DADOS ---
  db:
    image: mariadb:11.2
    container_name: lollipet-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 4j7fzytr
      MYSQL_DATABASE: lolliPet
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- SERVIÇO DO BACKEND ---
  api:
    build:
      context: ./backend-lolli-pet
      dockerfile: Dockerfile
    ports:
      # CORREÇÃO: Mapeando a porta INTERNA 3001 para a EXTERNA 3001
      - "3001:3001"
    volumes:
      - ./backend-lolli-pet:/app
      - /app/node_modules
    env_file:
      - ./backend-lolli-pet/.env
    depends_on:
      db:
        condition: service_healthy

  # --- SERVIÇO DO FRONTEND ---
  web:
    build:
      context: ./lolli-pet-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./lolli-pet-web:/app
      - /app/node_modules
    environment:
      # URL da API acessível pelo navegador (fora do Docker)
      - VITE_API_URL=http://localhost:3001

volumes:
  mariadb_data: